name: PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            7.0.100-rc.1.22431.12
            6.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Check formatting
        run: dotnet fantomas . -r --check
      - name: Restore dependencies
        run: dotnet restore ./telplin.sln
      - name: Build
        run: dotnet build --no-restore -c Release ./telplin.sln
      - name: Tests
        run: dotnet test --no-restore --no-build -c Release